Palladium-JazzHR/src/objects/Applicant__c.object
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Palladium-JazzHR/src/objects/Job_Application__c.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <label>Applicant</label>
        <referenceTo>Applicant__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Job_Listing__c</fullName>
        <label>Job Listing ID</label>
        <referenceTo>Job_Listing__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{000000}</displayFormat>
        <label>Job Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Palladium-JazzHR/src/objects/Job_Listing__c.object
<CustomObject>
    <fields>
        <fullName>JazzHR_Job_ID__c</fullName>
        <externalId>true</externalId>
        <label>JazzHR Job ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Job Listing</label>
    <nameField>
        <displayFormat>J-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Listing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Palladium-JazzHR/src/objects/Questionnaire__c.object
<CustomObject>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Applicant__c</referenceTo>
        <relationshipLabel>Questionnaires</relationshipLabel>
        <relationshipName>Questionnaire</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Questionnaire</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Questionnaire ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questionnaire</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Palladium-JazzHR/src/classes/TestJazzHRApplicantJourneyController.cls
/** Developer 	: Sachin/Vinit
 *  Date		: 11 March 2019
 *  Purpose		: Test class for JazzHR Applicant Journey Controller
 **/
@isTest
public class TestJazzHRApplicantJourneyController {
    static testMethod void testfetchApplicant(){
        JazzHRTestDataHandler handlerObj = new JazzHRTestDataHandler();
        Applicant__c applicantObj = handlerObj.createApplicant('prospect_20190125164225_AEOQV5MUGH5DTOJK','JazzHR');
        insert applicantObj;
        JazzHRApplicantJourneyController.fetchApplicant('test');
        
    }
    static testMethod void testgetApplicantsData(){
        JazzHRTestDataHandler handlerObj = new JazzHRTestDataHandler();
        Applicant__c insertSecondApplicant = handlerObj.createApplicant('prospect_20190125164225_AEOQV5MUGH5DTOJW','JazzHR');
        insert insertSecondApplicant;
        
        Job_Listing__c jobListingObj = new Job_Listing__c();
		jobListingObj.JazzHR_Job_ID__c = 'testId';
        insert jobListingObj;

        Job_Application__c jobApplication = new Job_Application__c();
        jobApplication.Applicant__c	= insertSecondApplicant.id;
        jobApplication.Job_Listing__c = jobListingObj.id;
        insert jobApplication;
        
        Questionnaire__c questionObject = new Questionnaire__c();
        questionObject.Applicant__c = insertSecondApplicant.Id;
        questionObject.Question__c ='Test Question';
        questionObject.Answer__c ='Test Answer';
        insert questionObject;
        JazzHRApplicantJourneyController.getApplicantsData(insertSecondApplicant.id);
    }
    
}