Palladium-JazzHR/src/objects/Applicant__c.object
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Palladium-JazzHR/src/objects/JazzHR_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Enable_Send_Email__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If checked, Applicant Sync option to Send Email will be activated. If Unchecked, Send Email option will be disabled.</description>
        <inlineHelpText>If checked, Applicant Sync option to Send Email will be activated. If Unchecked, Send Email option will be disabled.</inlineHelpText>
        <label>Enable Send Email</label>
        <type>Checkbox</type>
    </fields>
    <label>JazzHR Setting</label>
</CustomObject>

Palladium-JazzHR/src/classes/TestGetApplicationDetailController.cls
/**	Developer 	: Sachin/Vinit
 * 	Date 		: 17 March 2019
 *  Purpose     : test class for getapplicantDetails Controller
 **/
@isTest
public class TestGetApplicationDetailController {
    static testMethod void testgetSingleApplicantRecord(){
        // create applicant records
        JazzHRTestDataHandler handlerObj = new JazzHRTestDataHandler();
        Applicant__c insertFirstApplicant = handlerObj.createApplicant('prospect_20190125164225_AEOQV5MUGH5DTOJK','JazzHR');
        insert insertFirstApplicant;
        GetApplicantDetailController.getSingleApplicantRecord(insertFirstApplicant.Id);
    }
    static testMethod void testSendMail(){
        JazzHRTestDataHandler handlerObj = new JazzHRTestDataHandler();
        Applicant__c insertFirstApplicant = handlerObj.createApplicant('prospect_20190125164225_AEOQV5MUGH5DTOJK','JazzHR');
        insert insertFirstApplicant;
        JazzHR_Setting__c jazzHRSettingObj = new JazzHR_Setting__c();
        jazzHRSettingObj.Name = 'JazzHR';
        jazzHRSettingObj.Enable_Send_Email__c = true;
        insert jazzHRSettingObj;
        GetApplicantDetailController.sendEmail(insertFirstApplicant.Id);
    }
    
}