Palladium-JazzHR/src/objects/Applicant__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First Name</description>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Synced__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is synced from JazzHR?</description>
        <inlineHelpText>Is synced from JazzHR?</inlineHelpText>
        <label>Is Synced</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Sync_Date_Time__c</fullName>
        <label>Last Sync Date Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <formula>TRIM(LEFT (RIGHT(Location__c,  8 ), 4)) &amp; &apos; &apos; &amp; RIGHT(Location__c,  3 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Postal Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Palladium-JazzHR/src/objects/Job_Application__c.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <label>Applicant</label>
        <referenceTo>Applicant__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{000000}</displayFormat>
        <label>Job Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Palladium-JazzHR/src/objects/Questionnaire__c.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>Applicant__c</referenceTo>
        <relationshipLabel>Questionnaires</relationshipLabel>
        <relationshipName>Questionnaire</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Questionnaire</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Questionnaire ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questionnaire</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Palladium-JazzHR/src/classes/JazzHRApplicantJourneyController.cls
public class JazzHRApplicantJourneyController {
    @AuraEnabled
    public static List <sObject > fetchApplicant(String searchKeyWord) {
        system.debug('*********search Key'+searchKeyWord);
        String searchKey = '%' + searchKeyWord + '%';
        List < sObject  > returnList = new List < sObject  > ();
        List < sObject  > lstOfApplicant = [select id,Name,First_Name__c,Last_Name__c,Address__c,Location__c,Postal_Code__c,Source__c,Phone__c,Email__c,Last_Sync_Date_Time__c,Is_Synced__c from Applicant__c 
                                                where First_Name__c LIKE: searchKey OR  Last_Name__c LIKE:searchKey OR Phone__c LIKE:searchKey OR Email__c LIKE:searchKey LIMIT 10];
        
        for (sObject  acc: lstOfApplicant) {
            returnList.add(acc);
        }
        return returnList;
    }
    
    public static List<Schema.FieldSetMember> getFields(string objectname) {
        if(objectname == 'Job_Applications__r')
            return SObjectType.Job_Application__c.FieldSets.Job_Applicant_Field_Set_For_Lex_Cmp.getFields();
        if(objectname == 'Questionnaire__r')
            return SObjectType.Questionnaire__c.FieldSets.Questionnaire_Field_Set_For_Lex_Cmp.getFields();
        if(objectname == 'Applicant__c')
             return SObjectType.Applicant__c.FieldSets.Applicant_Field_Set_For_Lex_Cmp.getFields();
            
        else
            return null;
    }
    
    @AuraEnabled
    public static Applicant__c getApplicantsData(string applicantId){
        Applicant__c ApplicantDetails = new Applicant__c();
        try{
            string query = 'SELECT Id, (' + getQueryString('Job_Applications__r') + 
                '), (' + getQueryString('Questionnaire__r') + '), '+ getFieldList('Applicant__c') + ' FROM Applicant__c where Id =:applicantId';
            system.debug('query: ' + query);
            ApplicantDetails =  Database.query(query);
            system.debug('****ApplicantDetails: '+ApplicantDetails); 
        }catch(Exception oEx){
            Logger.Log('Error','Line Number: ' + oEx.getLineNumber() + ' Message: ' + oEx.getMessage(), 'JazzHRApplicantJourneyController.getApplicantsData', '');   
            system.debug('Error Line Number: ' + oEx.getLineNumber() + ' Message: ' + oEx.getMessage());
            ApplicantDetails = null;
        }
        return ApplicantDetails;
    }
    
    
    public static String getQueryString(string objectname) {
        String query = 'SELECT ';
        for(Schema.FieldSetMember f : getFields(objectname)) {
            query += f.getFieldPath() + ',';
        }
        query = query.substring(0, query.length() - 1);
        query += ' FROM ' + objectname;
        return query;
    }  
    
     public static String getFieldList(string objectname) {
        String query = '';
        for(Schema.FieldSetMember f : getFields(objectname)) {
            query += f.getFieldPath() + ',';
        }
        query = query.substring(0, query.length() - 1);
        return query;
    }
}