Palladium-JazzHR/src/objects/Applicant__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First Name</description>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JazzHR_Applicant_ID__c</fullName>
        <externalId>true</externalId>
        <label>JazzHR Applicant ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Palladium-JazzHR/src/objects/Job_Application__c.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <label>Applicant</label>
        <referenceTo>Applicant__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Job_Listing__c</fullName>
        <label>Job Listing ID</label>
        <referenceTo>Job_Listing__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{000000}</displayFormat>
        <label>Job Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Palladium-JazzHR/src/objects/Job_Listing__c.object
<CustomObject>
    <fields>
        <fullName>JazzHR_Job_ID__c</fullName>
        <externalId>true</externalId>
        <label>JazzHR Job ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Job Listing</label>
    <nameField>
        <displayFormat>J-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Listing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Palladium-JazzHR/src/classes/TestBatchDeleteJobApplications.cls
/** Date : 19/06/2019
 *  Purpose : Test class for BatchDeleteJobApplications
**/
@isTest
public class TestBatchDeleteJobApplications {
    public static testMethod void testBatchDeleteJobApplication(){
        
        // create test records applicant, job listing, and job application
        
        Applicant__c appObj = new Applicant__c();
        appObj.Email__c= 'test@test.com';
        appObj.First_Name__c = 'testFirstName';
        appObj.Last_Name__c = 'testLastName';
        appObj.JazzHR_Applicant_ID__c = 'prospect_20190125164225_AEOQV5MUGH5DTOJK';
        insert appObj;
        // create job listing
        Job_Listing__c jobListingObj = new Job_Listing__c();
        jobListingObj.JazzHR_Job_ID__c = 'job_20181126172240_AX3UHKDC1UNW1LSJ';
        insert jobListingObj;
        
        // create job application
        Job_Application__c jobApplicatonObj = new Job_Application__c();
        jobApplicatonObj.Applicant__c = appObj.id;
        jobApplicatonObj.Job_Listing__c = jobListingObj.id;
        insert jobApplicatonObj;
        
        BatchDeleteJobApplications batchObj = new BatchDeleteJobApplications();
        database.executeBatch(batchObj);
    }
}