Palladium-JazzHR/src/objects/Applicant__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apply_Date__c</fullName>
        <label>Apply Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Can_Work_Evenings__c</fullName>
        <label>Can Work Evenings</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Can_Work_Overtime__c</fullName>
        <label>Can Work Overtime</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Can_Work_Weekends__c</fullName>
        <label>Can Work Weekends</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Citizenship_Status__c</fullName>
        <label>Citizenship Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>College__c</fullName>
        <label>College</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First Name</description>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JazzHR_Applicant_ID__c</fullName>
        <externalId>true</externalId>
        <label>JazzHR Applicant ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>JazzHR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TalentPool</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Palladium-JazzHR/src/classes/JazzHRTestDataHandler.cls
/**
 * Developer		: Sachin/Vinit
 * Date				: 29 Jan 2019
 * Purpose			: Class for Test Class Data Handler
**/
public class JazzHRTestDataHandler {
  public Applicant__c createApplicant(string jazzHRApplicantId, string applicantType){
        Applicant__c appObj = new Applicant__c();
        appObj.JazzHR_Applicant_ID__c = jazzHRApplicantId;
      appObj.Email__c= 'test@test.com';
      appObj.First_Name__c = 'testFirstName';
      appObj.Last_Name__c = 'testLastName';
      
      appObj.Address__c='testaddress';
      appObj.Apply_Date__c = date.today();
      appObj.Can_Work_Evenings__c ='yes';
      appObj.Can_Work_Overtime__c = 'no';
      appObj.Can_Work_Weekends__c = 'yes';
      appObj.Citizenship_Status__c = 'test';
      appObj.College__c = 'test';
      appObj.Type__c = applicantType;
        return appObj;
    }
    public Lead createLead(string email){
        Lead l = new Lead();
        l.Email = email;
        l.LastName = 'test';
        return l;
    }
   
    
}